---
- hosts: 'incidents'
  become: 'yes'
  roles:
    - 'City-of-Bloomington.mysql'
    - 'City-of-Bloomington.tomcat'
  tasks:
    - name: "Create installation directories"
      file:
        path: "{{ item }}"
        state: "directory"
        owner: "tomcat"
        group: "staff"
      with_items:
        - "{{ incidents_backup_path  }}"
        - "{{ incidents_site_home    }}"
        - "{{ incidents_site_home    }}/conf"
        - "{{ incidents_site_home    }}/files"

    - name: "Create mysql database"
      mysql_db:
        config_file: "{{ mysql_defaults_extra_file }}"
        name: "{{ incidents_db.name }}"
        state: "present"
      no_log: "True"

    - name: "Create mysql user for site"
      mysql_user:
        name:     "{{ incidents_db.user }}"
        password: "{{ incidents_db.pass }}"
        priv:     "{{ incidents_db.name }}.*:ALL"
        state: "present"
        config_file: "{{ mysql_defaults_extra_file }}"
      no_log: "True"

    - name: 'Configure context'
      template:
        src:  'context.xml'
        dest: "/etc/{{ tomcat_package }}/Catalina/localhost/incidents.xml"
      notify: 'tomcat_restart'

    - name: 'Configure application'
      template:
        src:  "{{ item }}"
        dest: "{{ incidents_site_home }}/conf/{{ item }}"
      with_items:
        - 'application.properties'
        - 'logback.xml'
      notify: 'tomcat_restart'

    - name: 'Install WAR file'
      copy:
        src:  '../target/incidents.war'
        dest: "{{ incidents_install_path }}/{{ incidents_app_name }}.war"
      notify: "tomcat_restart"
...
